### ISSUE TITLE
Support missing for CloudFormation exports

### ISSUE THREAD

**Issue by mmatlik** [newrelic/aws-log-ingestion#16]
Hi,

Please consider adding support for cross-stack CloudFormation imports & exports.

**Use case:**
In order to subscribe the [CloudWatch LogGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html#cfn-cwl-subscriptionfilter-destinationarn) to a lambda - the `DestinationArn` must be provided. If an existing stack exports this value - then the ARN can be imported from the consumer’s CF code directly, by referencing the export via its `Name`. 

**Adding support:**
Given the provided CF [template.yaml](https://github.com/newrelic/aws-log-ingestion/blob/master/template.yaml#L111), enabling the support could be enabled by adding the following Outputs section:

```
Outputs:
  LogIngestionFunctionArn:
    Condition: NoRole
    Description: Log ingestion lambda function ARN
    Value: !GetAtt NewRelicLogIngestionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LogIngestionFunctionArn"
  LogIngestionFunctionNoCapArn:
    Condition: NoCap
    Description: Log ingestion capless lambda function ARN
    Value: !GetAtt NewRelicLogIngestionFunctionNoCap.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LogIngestionFunctionArn"
```

Thank you

**Comment by drAlberT** [comment]
Good point.

I'd use a new parameter to make these export names customisable anyway. Something like `LogIngestionFunctionArnExportName` 

The proposed Output became:
```
Outputs:
  LogIngestionFunctionArn:
    Condition: NoRole
    Description: Log ingestion lambda function ARN
    Value: !GetAtt NewRelicLogIngestionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-${LogIngestionFunctionArnExportName}"
  LogIngestionFunctionNoCapArn:
    Condition: NoCap
    Description: Log ingestion capless lambda function ARN
    Value: !GetAtt NewRelicLogIngestionFunctionNoCap.Arn
    Export:
      Name: !Sub "${AWS::StackName}-${LogIngestionFunctionArnExportName}"
```

**Comment by mmatlik** [comment]
Great idea, @drAlberT. Totally supporting that 👍

**Comment by mmatlik** [comment]
@MattWhelan - any updates on this? Thank you.

**Comment by MattWhelan** [comment]
This seems like a useful, straightforward change. I hope to have a PR shortly.
