### ISSUE TITLE
Unable to import module 'function': No module named 'urllib2'

### ISSUE THREAD

**Issue by sp4ceman** [newrelic/aws-log-ingestion#4]
![image](https://user-images.githubusercontent.com/243214/47897580-146f9200-de7b-11e8-8024-d0a488c8e06e.png)

this is the error received when installing from the aws serverless application repository

**Comment by javimb** [comment]
We just released a new version of this function and it has been migrated to Python 3.
Looks like AWS has created the function using the new code but selecting Python 2.7 as runtime. Could you create it again and check which is the runtime declared in the SAM template?

**Comment by sp4ceman** [comment]
correct - you can switch to 2.x using the lambda console - no need to redeploy. this will fix it
