### ISSUE TITLE
Recent change (PR 88 ) to allow multiple versions per account appears to break newrelic-lambda-cli

### ISSUE THREAD

**Issue by Brendmanitix** [newrelic/aws-log-ingestion#89]
The change here, which adds `AWS::StackId` suffix to the lambda name (https://github.com/newrelic/aws-log-ingestion/pull/88) breaks several of the commands in the `newrelic-lambda-cli`. See: https://github.com/newrelic/newrelic-lambda-cli/issues/240 for details.

**Comment by chaudharysaket** [comment]
The new release of the `newrelic-lambda-cli` fixes the issue with stack by introducing parameter to provide `--stackname`. Please refer to [release notes](https://github.com/newrelic/newrelic-lambda-cli/releases/tag/v0.9.0)
